version: '2'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres